---
title: ""
output: github_document
---

# lastdose 

Calculate the time since and amount of the last dose. 

```{r,include=FALSE}
knitr::opts_chunk$set(comment = '.', message=FALSE, warning = FALSE, 
                      fig.path="man/figures/readme-")
```


```{r,message=FALSE}
library(lastdose)
library(tidyverse)
theme_set(theme_bw())

file <- system.file("csv/data1.csv", package = "lastdose")

df <- read.csv(file) 

head(df)
```

## A PK profile
```{r}
df %>% filter(evid==1) %>% count(time,amt,addl)

ggplot(df, aes(time,DV)) + geom_line() + theme_bw()
```


# Plot last dose versus time
```{r}
x <- lastdose(df)

df <- mutate(df, tad = x$tad, ldos = x$ldos)

ggplot(df, aes(time,ldos)) + geom_line()
```

# Plot time after dose versus time

```{r}
ggplot(df, aes(time,tad)) + geom_line()

ggplot(df, aes(time,tad)) + geom_line() + 
  scale_x_continuous(breaks = seq(0,72,4), limits=c(0,72)) + 
  scale_y_continuous(breaks = seq(0,24,4), limits=c(0,24)) 

```

# All doses explicit in the data set
```{r}
df2 <- mrgsolve::realize_addl(df) 

x <- lastdose(df2)

df2 <- mutate(df2, tad = x$tad, ldos = x$ldos)

ggplot(df2, aes(time,tad)) + geom_line()

ggplot(df2, aes(time,tad)) + geom_line() + 
  scale_x_continuous(breaks = seq(0,72,4), limits = c(0,72)) + 
  scale_y_continuous(breaks = seq(0,24,4))
```


# How does it perform on bigger data?

Same setup as the previous profile, but more individuals.

```{r}
file <- system.file("csv/data_big.RDS", package = "lastdose")

big <- readRDS(file)

dim(big)

length(unique(big$ID))

system.time(x2 <- lastdose(big))
```

## Compare against the single profile
```{R}
system.time(x1 <- lastdose(df))

x3 <- filter(x2, big[["ID"]]==1)

identical(x1,x3)

```

