# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lastdose_impl <- function(id, time, amt, evid, addl, ii, fill, back_calc, sort1, comment) {
    .Call(`_lastdose_lastdose_impl`, id, time, amt, evid, addl, ii, fill, back_calc, sort1, comment)
}

